---
apiVersion: v1
kind: Secret
metadata:
  name: disconnected-registry-pull-secret
  namespace: sno2
stringData:
  .dockerconfigjson: '{"auths":{"quay.tnc.bootcamp.lab:8443":{"auth":"xxxxxx"},"registry.redhat.io":{"auth":"xxxxxxxx"}}}'

  type: kubernetes.io/dockerconfigjson

